---
apiVersion: v1
kind: Namespace
metadata:
  name: customer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
  namespace: customer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: customer
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 0%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: customer
    spec:
      containers:
        - name: customer
          image: dnakano/microservice-handson/catolog:latest
          imagePullPolicy: Never
          env:
            - name: LISTEN_PORT
              value: "5000"
            - name: ITEM_HOST
              value: item
            - name: ITEM_PORT
              value: "5000"
            - name: CUSTOMER_HOST
              value: customer
            - name: CUSTOMER_PORT
              value: "5000"
            - name: DB_HOST
              value: db
            - name: DB_PORT
              value: "5000"
          resources:
            limits:
              cpu: 500m
              memory: 50Mi
            requests:
              cpu: 500m
              memory: 50Mi

---
apiVersion: v1
kind: Service
metadata:
  name: customer
  namespace: customer
spec:
  type: ClusterIP
  selector:
    app: customer
  ports:
    - name: grpc
      protocol: TCP
      port: 5000
      targetPort: 5000
